export {default as Home } from "./Home/Home"
export {default as NotFound } from "./NotFound/NotFound"
export {default as How } from "./How/How"
export {default as DetailGame } from "./DetailGame/DetailGame"
export {default as CartPage } from "./CartPage/CartPage"
